const KEY = 'preventivos-vallada-v1';
const MESES = ['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'];
const defaultState = () => ({ settings: { nombre: 'José Ramón Ferrer Blasco', codigo: '213', base: 'Sedavi / Valencia – Vallada / Valencia', umbral: 6, fijo: 40, hora: 10, emailOficinas: '' }, servicios: [], observaciones: {} });
function load() { try { return Object.assign(defaultState(), JSON.parse(localStorage.getItem(KEY) || '{}')); } catch { return defaultState(); } }
function save() { localStorage.setItem(KEY, JSON.stringify(state)); }
let state = load();
if (!state.settings) state.settings = defaultState().settings;
if (!state.servicios) state.servicios = [];
if (!state.observaciones) state.observaciones = {};
const now = new Date();
let mesSel = now.getMonth();
let anioSel = now.getFullYear();
let editId = null;
function pad(n) { return String(n).padStart(2, '0'); }
function toMin(hhmm) { if (!hhmm) return null; const [h, m] = hhmm.split(':').map(Number); return h * 60 + m; }
function minutosReloj(llegada, fin) { const a = toMin(llegada), b = toMin(fin); if (a == null || b == null) return null; let d = b - a; if (d < 0) d += 24 * 60; return d; }
function fmtHoras(min) { if (min == null) return '—'; return `${Math.floor(min / 60)}:${pad(min % 60)}`; }
function pvpDe(s) { if (s.manual !== '' && s.manual != null) return Number(s.manual); const min = s.cobrarMin != null && s.cobrarMin !== '' ? Number(s.cobrarMin) : minutosReloj(s.llegada, s.fin); if (min == null) return 0; const h = Math.round((min / 60) * 100) / 100; if (h < Number(state.settings.umbral)) return Number(state.settings.fijo); return Math.round(h * Number(state.settings.hora) * 100) / 100; }
function serviciosMes() { return state.servicios.filter(s => s.mes === mesSel && s.anio === anioSel).sort((a, b) => (a.fecha || '').localeCompare(b.fecha || '')); }
function totMes() { const list = serviciosMes(); let min = 0, euro = 0; list.forEach(s => { const m = minutosReloj(s.llegada, s.fin); if (m) min += m; euro += pvpDe(s); }); return { n: list.length, min, euro }; }
function uid() { return Date.now().toString(36) + Math.random().toString(36).slice(2, 7); }
function go(page) { document.querySelectorAll('.page').forEach(p => p.classList.toggle('on', p.id === 'page-' + page)); document.querySelectorAll('nav.tab button').forEach(b => b.classList.toggle('on', b.dataset.page === page)); if (page === 'mes') renderMes(); if (page === 'resumen') renderResumen(); if (page === 'ajustes') renderAjustes(); }
function renderMes() { document.getElementById('sel-mes').value = mesSel; document.getElementById('sel-anio').value = anioSel; const t = totMes(); document.getElementById('t-n').textContent = t.n; document.getElementById('t-h').textContent = fmtHoras(t.min); document.getElementById('t-e').textContent = t.euro.toFixed(2) + ' €'; const list = serviciosMes(); const box = document.getElementById('lista'); if (!list.length) { box.innerHTML = '<div class="empty">Sin servicios este mes.<br>Pulsa + para añadir uno.</div>'; return; } box.innerHTML = list.map(s => `<article class="card"><div class="row1"><span class="fecha">${s.fecha || ''}</span><span class="pvp">${pvpDe(s).toFixed(2)} €</span></div><div class="dest">${s.destino || '—'}</div><div class="ev">${s.evento || ''}</div><div class="hrs"><span>${s.llegada || '—'} → ${s.fin || '—'}</span><span>Reloj ${fmtHoras(minutosReloj(s.llegada, s.fin))}</span>${s.manual ? '<span class="badge">MANUAL</span>' : ''}</div><div class="actions"><button class="mini btn-ghost" onclick="editar('${s.id}')">Editar</button><button class="mini btn-danger" onclick="borrar('${s.id}')">Borrar</button></div></article>`).join(''); }
function renderResumen() { const t = totMes(); const list = serviciosMes(); const cortos = list.filter(s => { const m = minutosReloj(s.llegada, s.fin); return m != null && (m / 60) < Number(state.settings.umbral); }).length; document.getElementById('res-body').innerHTML = `<div class="totals"><div class="tot"><b>${t.n}</b><span>Servicios</span></div><div class="tot"><b>${fmtHoras(t.min)}</b><span>Horas reloj</span></div><div class="tot"><b>${t.euro.toFixed(2)} €</b><span>Según regla</span></div></div><div class="card" style="margin:12px 16px"><div>Cortos (< ${state.settings.umbral} h): <b>${cortos}</b></div><div>Largos: <b>${t.n - cortos}</b></div></div><div class="card" style="margin:12px 16px"><label>Observaciones de ${MESES[mesSel]}</label><textarea class="obs" id="obs-mes" onchange="guardarObs()">${state.observaciones[anioSel+'-'+mesSel] || ''}</textarea></div><div style="padding:0 16px 16px;display:flex;flex-direction:column;gap:8px"><button class="btn-primary" onclick="exportarExcel()">Exportar Excel para Grok</button><button class="btn-ghost" onclick="compartirMes()">Compartir resumen</button><p class="hint">Se descarga un .xlsx. Archivos → OneDrive y pásamelo aquí.</p></div>`; }
function guardarObs() { const el = document.getElementById('obs-mes'); if (!el) return; state.observaciones[anioSel + '-' + mesSel] = el.value; save(); }
function renderAjustes() { const s = state.settings; document.getElementById('set-nombre').value = s.nombre; document.getElementById('set-codigo').value = s.codigo; document.getElementById('set-base').value = s.base; document.getElementById('set-umbral').value = s.umbral; document.getElementById('set-fijo').value = s.fijo; document.getElementById('set-hora').value = s.hora; document.getElementById('set-email').value = s.emailOficinas || ''; }
function guardarAjustes() { state.settings = { nombre: document.getElementById('set-nombre').value, codigo: document.getElementById('set-codigo').value, base: document.getElementById('set-base').value, umbral: Number(document.getElementById('set-umbral').value) || 6, fijo: Number(document.getElementById('set-fijo').value) || 40, hora: Number(document.getElementById('set-hora').value) || 10, emailOficinas: document.getElementById('set-email').value }; save(); alert('Ajustes guardados'); go('mes'); }
function nuevo() { editId = null; document.getElementById('f-titulo').textContent = 'Nuevo servicio'; ['f-fecha','f-destino','f-evento','f-llegada','f-fin','f-cobrar','f-manual','f-notas'].forEach(id => document.getElementById(id).value = ''); actualizarPreview(); go('form'); }
function editar(id) { const s = state.servicios.find(x => x.id === id); if (!s) return; editId = id; document.getElementById('f-titulo').textContent = 'Editar servicio'; document.getElementById('f-fecha').value = s.fecha || ''; document.getElementById('f-destino').value = s.destino || ''; document.getElementById('f-evento').value = s.evento || ''; document.getElementById('f-llegada').value = s.llegada || ''; document.getElementById('f-fin').value = s.fin || ''; document.getElementById('f-cobrar').value = s.cobrarMin ? fmtHoras(Number(s.cobrarMin)) : ''; document.getElementById('f-manual').value = s.manual || ''; document.getElementById('f-notas').value = s.notas || ''; actualizarPreview(); go('form'); }
function parseHorasCampo(txt) { if (!txt) return null; const p = txt.replace(',', ':').split(':'); if (p.length === 1) return Math.round(Number(p[0]) * 60); return Number(p[0]) * 60 + Number(p[1] || 0); }
function actualizarPreview() { const fake = { llegada: document.getElementById('f-llegada').value, fin: document.getElementById('f-fin').value, cobrarMin: parseHorasCampo(document.getElementById('f-cobrar').value), manual: document.getElementById('f-manual').value }; document.getElementById('prev-h').textContent = fmtHoras(minutosReloj(fake.llegada, fake.fin)); document.getElementById('prev-e').textContent = pvpDe(fake).toFixed(2) + ' €'; }
function guardarServicio(ev) { ev.preventDefault(); const fecha = document.getElementById('f-fecha').value; if (!fecha) { alert('Pon la fecha'); return; } const d = new Date(fecha + 'T12:00:00'); const rec = { id: editId || uid(), fecha, mes: d.getMonth(), anio: d.getFullYear(), destino: document.getElementById('f-destino').value.trim(), evento: document.getElementById('f-evento').value.trim(), llegada: document.getElementById('f-llegada').value, fin: document.getElementById('f-fin').value, cobrarMin: parseHorasCampo(document.getElementById('f-cobrar').value), manual: document.getElementById('f-manual').value, notas: document.getElementById('f-notas').value.trim() }; if (editId) { state.servicios[state.servicios.findIndex(x => x.id === editId)] = rec; } else { state.servicios.push(rec); } save(); mesSel = rec.mes; anioSel = rec.anio; go('mes'); }
function borrar(id) { if (!confirm('¿Borrar este servicio?')) return; state.servicios = state.servicios.filter(s => s.id !== id); save(); renderMes(); }
function compartirMes() { const t = totMes(); const list = serviciosMes(); let txt = `PREVENTIVOS ${MESES[mesSel]} ${anioSel}\n${state.settings.nombre} · cód. ${state.settings.codigo}\n\n`; list.forEach(s => { txt += `${s.fecha}  ${s.destino}  ${s.evento}\n  ${s.llegada}-${s.fin}  ${fmtHoras(minutosReloj(s.llegada,s.fin))}  ${pvpDe(s).toFixed(2)}€\n`; }); txt += `\nTOTAL  ${t.n} servicios  ${fmtHoras(t.min)}  ${t.euro.toFixed(2)} €\n`; if (navigator.share) navigator.share({ title: 'Preventivos ' + MESES[mesSel], text: txt }); else { navigator.clipboard.writeText(txt); alert('Resumen copiado'); } }
function exportarExcel() { const list = [...state.servicios].sort((a, b) => (a.fecha || '').localeCompare(b.fecha || '')); const rows = [['FECHA','DESTINO','NOMBRE DEL EVENTO','H. LLEGADA','H. FIN','H. RELOJ','H. A COBRAR','PVP (€)','€ MANUAL','NOTAS','MES','AÑO']]; list.forEach(s => { rows.push([s.fecha||'', s.destino||'', s.evento||'', s.llegada||'', s.fin||'', fmtHoras(minutosReloj(s.llegada,s.fin)), (s.cobrarMin!=null && s.cobrarMin!=='') ? fmtHoras(Number(s.cobrarMin)) : '', pvpDe(s), s.manual||'', s.notas||'', MESES[s.mes]||'', s.anio||'']); }); rows.push([]); rows.push(['TOTAL SERVICIOS', list.length]); rows.push(['TOTAL €', list.reduce((a,s)=>a+pvpDe(s),0)]); rows.push(['CONDUCTOR', state.settings.nombre, 'COD', state.settings.codigo]); const nombre = 'Preventivos_export_' + anioSel + '_' + MESES[mesSel] + '.xlsx'; if (window.XLSX) { const wb = XLSX.utils.book_new(); const ws = XLSX.utils.aoa_to_sheet(rows); XLSX.utils.book_append_sheet(wb, ws, 'Servicios'); XLSX.writeFile(wb, nombre); return; } const csv = rows.map(r => r.map(v => '"'+String(v).replace(/"/g,'""')+'"').join(';')).join('\n'); const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob(['\ufeff'+csv], {type:'text/csv;charset=utf-8'})); a.download = nombre.replace('.xlsx','.csv'); a.click(); }
function exportarJSON() { const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'})); a.download = 'preventivos-vallada.json'; a.click(); }
function importarJSON(file) { const r = new FileReader(); r.onload = () => { try { const data = JSON.parse(r.result); if (!data.servicios) throw 0; state = Object.assign(defaultState(), data); save(); alert('Importados: ' + state.servicios.length); go('mes'); } catch(e) { alert('No se pudo importar'); } }; r.readAsText(file); }
document.addEventListener('DOMContentLoaded', () => { const sm = document.getElementById('sel-mes'); MESES.forEach((m,i) => { const o = document.createElement('option'); o.value = i; o.textContent = m; sm.appendChild(o); }); sm.value = mesSel; document.getElementById('sel-anio').value = anioSel; ['f-llegada','f-fin','f-cobrar','f-manual'].forEach(id => document.getElementById(id).addEventListener('input', actualizarPreview)); renderMes(); if ('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js'); });
